### ISSUE TITLE
[Documentation] Query component no longer supported?

### ISSUE THREAD

**Issue by freeatnet** [adamsoffer/next-apollo#49]
@adamsoffer thank you for doing all the work you do on this library!

I had a bit of an issue setting up a new project with next-apollo last night. The most jarring part of it, I suppose, is I had a chance to integrate this library in another project just last month and following the documentation worked like a charm.

I eventually stumbled upon https://github.com/adamsoffer/next-apollo-example and got things to work by looking at its code; however, I still have a couple of questions:

1. Do I understand correctly that next-apollo no longer supports the Query component as of 3.0?
2. Did I end up with a correct [set of dependencies](https://github.com/freeatnet/next-apollo-woes/blob/master/package.json) or should I expect it to bite me at some point?
3. Is there anything I can do to help improve next-apollo's documentation?

P.S. I documented the struggles [here](https://github.com/freeatnet/next-apollo-woes) in case anyone faces the same issues in the meantime.

**Comment by adamsoffer** [comment]
Hey @freeatnet ! Yeah, I recently published v3.0.0 to support `apollo-hooks`. Sorry for the confusion. Someone recommended I start publishing a changelog to avoid such confusion in the future. I'll make sure to do that when publishing future versions.

1. I haven't tried using the Query component with this library so I'm not sure! I found the hooks to be way less verbose and easier to read so I haven't even bothered trying the query component with 3.0.0.
2. Deps look good, except `react-apollo` is out of beta since the time of writing
3. Yes! Feel free to submit PRs with documentation improvements. Would be v grateful 🙏
